# fly.toml app configuration file generated for shamrock on 2024-01-22T21:35:30-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shamrock"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
