name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out your repository using git
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build Vite project
      run: bun run build --base=/shamrock
      continue-on-error: true

    - name: Check for build output
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "dist/index.html"

    - name: Handle build failure
      if: steps.check_files.outputs.files_exists == 'false'
      run: |
        echo "Build seems to have failed. Check your build process."
        exit 1

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
